<?php

declare(strict_types=1);

/*
 * OrdersLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace OrdersLib;

/**
 * Environments available for API
 */
class Environment
{
    /**
     * PayPal Sandbox Environment
     */
    public const PRODUCTION = 'production';

    /**
     * PayPal Live Environment
     */
    public const ENVIRONMENT2 = 'environment2';
}
