<?php

declare(strict_types=1);

/*
 * APIMATICCalculatorByClientLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace APIMATICCalculatorByClientLib\Tests;

use APIMATICCalculatorByClientLib\APIMATICCalculatorByClientClient;
use APIMATICCalculatorByClientLib\APIMATICCalculatorByClientClientBuilder;
use APIMATICCalculatorByClientLib\Authentication\CustomHeaderAuthenticationCredentialsBuilder;
use Core\Types\CallbackCatcher;

class ClientFactory
{
    public static function create(CallbackCatcher $httpCallback): APIMATICCalculatorByClientClient
    {
        $clientBuilder = APIMATICCalculatorByClientClientBuilder::init();
        $clientBuilder = self::addConfigurationFromEnvironment($clientBuilder);
        $clientBuilder = self::addTestConfiguration($clientBuilder);
        return $clientBuilder->httpCallback($httpCallback)->build();
    }

    public static function addTestConfiguration(
        APIMATICCalculatorByClientClientBuilder $builder
    ): APIMATICCalculatorByClientClientBuilder {
        return $builder
            ->customHeaderAuthenticationCredentials(
                CustomHeaderAuthenticationCredentialsBuilder::init('My auth my rule')
            );
    }

    public static function addConfigurationFromEnvironment(
        APIMATICCalculatorByClientClientBuilder $builder
    ): APIMATICCalculatorByClientClientBuilder {
        $timeout = getenv('APIMATIC_CALCULATOR_BY_CLIENT_LIB_TIMEOUT');
        $numberOfRetries = getenv('APIMATIC_CALCULATOR_BY_CLIENT_LIB_NUMBER_OF_RETRIES');
        $maximumRetryWaitTime = getenv('APIMATIC_CALCULATOR_BY_CLIENT_LIB_MAXIMUM_RETRY_WAIT_TIME');
        $environment = getenv('APIMATIC_CALCULATOR_BY_CLIENT_LIB_ENVIRONMENT');
        $environment3 = getenv('APIMATIC_CALCULATOR_BY_CLIENT_LIB_ENVIRONMENT_3');
        $environment2 = getenv('APIMATIC_CALCULATOR_BY_CLIENT_LIB_ENVIRONMENT_2');

        if (!empty($timeout) && \is_numeric($timeout)) {
            $builder->timeout(intval($timeout));
        }

        if (!empty($numberOfRetries) && \is_numeric($numberOfRetries)) {
            $builder->numberOfRetries(intval($numberOfRetries));
        }

        if (!empty($maximumRetryWaitTime) && \is_numeric($maximumRetryWaitTime)) {
            $builder->maximumRetryWaitTime(intval($maximumRetryWaitTime));
        }

        if (!empty($environment)) {
            $builder->environment($environment);
        }

        if (!empty($environment3)) {
            $builder->environment3($environment3);
        }

        if (!empty($environment2)) {
            $builder->customHeaderAuthenticationCredentials(
                CustomHeaderAuthenticationCredentialsBuilder::init($environment2)
            );
        }

        return $builder;
    }
}
