<?php

declare(strict_types=1);

/*
 * APIMATICCalculatorByClientLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace APIMATICCalculatorByClientLib;

/**
 * Interface for defining the behavior of Authentication.
 */
interface CustomHeaderAuthenticationCredentials
{
    /**
     * String value for environment.
     */
    public function getEnvironment(): string;

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $environment api-token environment custom header auth
     */
    public function equals(string $environment): bool;
}
