<?php

declare(strict_types=1);

/*
 * APIMATICCalculatorByClientLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace APIMATICCalculatorByClientLib\Authentication;

use Core\Authentication\CoreAuth;
use APIMATICCalculatorByClientLib\ConfigurationDefaults;
use Core\Request\Parameters\HeaderParam;
use APIMATICCalculatorByClientLib\CustomHeaderAuthenticationCredentials;

/**
 * Utility class for authorization and token management.
 */
class CustomHeaderAuthenticationManager extends CoreAuth implements CustomHeaderAuthenticationCredentials
{
    /**
     * @var array
     */
    private $config;

    public function __construct(array $config)
    {
        $this->config = $config;
        parent::__construct(HeaderParam::init('environment', $this->getEnvironment())->requiredNonEmpty());
    }

    /**
     * String value for environment.
     */
    public function getEnvironment(): string
    {
        return $this->config['environment2'] ?? ConfigurationDefaults::ENVIRONMENT_2;
    }

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $environment api-token environment custom header auth
     */
    public function equals(string $environment): bool
    {
        return $environment == $this->getEnvironment();
    }
}
