<?php

declare(strict_types=1);

/*
 * PaypalRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaypalRestApisLib;

/**
 * Environments available for API
 */
class Environment
{
    /**
     * PayPal Live Environment
     */
    public const PRODUCTION = 'Production';

    /**
     * PayPal Sandbox Environment
     */
    public const SANDBOX = 'Sandbox';
}
