<?php

declare(strict_types=1);

/*
 * OrdersLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace OrdersLib\Models\Builders;

use Core\Utils\CoreHelper;
use OrdersLib\Models\EPSPaymentRequest;
use OrdersLib\Models\ExperienceContext;

/**
 * Builder for model EPSPaymentRequest
 *
 * @see EPSPaymentRequest
 */
class EPSPaymentRequestBuilder
{
    /**
     * @var EPSPaymentRequest
     */
    private $instance;

    private function __construct(EPSPaymentRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new EPS Payment Request Builder object.
     *
     * @param string $name
     * @param string $countryCode
     */
    public static function init(string $name, string $countryCode): self
    {
        return new self(new EPSPaymentRequest($name, $countryCode));
    }

    /**
     * Sets experience context field.
     *
     * @param ExperienceContext|null $value
     */
    public function experienceContext(?ExperienceContext $value): self
    {
        $this->instance->setExperienceContext($value);
        return $this;
    }

    /**
     * Initializes a new EPS Payment Request object.
     */
    public function build(): EPSPaymentRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
