<?php

declare(strict_types=1);

/*
 * OrdersLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace OrdersLib\Models\Builders;

use Core\Utils\CoreHelper;
use OrdersLib\Models\ExperienceContext;
use OrdersLib\Models\IDEALPaymentRequest;

/**
 * Builder for model IDEALPaymentRequest
 *
 * @see IDEALPaymentRequest
 */
class IDEALPaymentRequestBuilder
{
    /**
     * @var IDEALPaymentRequest
     */
    private $instance;

    private function __construct(IDEALPaymentRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new IDEAL Payment Request Builder object.
     *
     * @param string $name
     * @param string $countryCode
     */
    public static function init(string $name, string $countryCode): self
    {
        return new self(new IDEALPaymentRequest($name, $countryCode));
    }

    /**
     * Sets bic field.
     *
     * @param string|null $value
     */
    public function bic(?string $value): self
    {
        $this->instance->setBic($value);
        return $this;
    }

    /**
     * Sets experience context field.
     *
     * @param ExperienceContext|null $value
     */
    public function experienceContext(?ExperienceContext $value): self
    {
        $this->instance->setExperienceContext($value);
        return $this;
    }

    /**
     * Initializes a new IDEAL Payment Request object.
     */
    public function build(): IDEALPaymentRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
