<?php

declare(strict_types=1);

/*
 * OrdersLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace OrdersLib\Models\Builders;

use Core\Utils\CoreHelper;
use OrdersLib\Models\VaultInstruction;

/**
 * Builder for model VaultInstruction
 *
 * @see VaultInstruction
 */
class VaultInstructionBuilder
{
    /**
     * @var VaultInstruction
     */
    private $instance;

    private function __construct(VaultInstruction $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Vault Instruction Builder object.
     */
    public static function init(): self
    {
        return new self(new VaultInstruction());
    }

    /**
     * Initializes a new Vault Instruction object.
     */
    public function build(): VaultInstruction
    {
        return CoreHelper::clone($this->instance);
    }
}
