<?php

declare(strict_types=1);

/*
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace APIMATICCalculatorLib;

/**
 * Environments available for API
 */
class Environment
{
    /**
     * This environment connect to the LIVE calculator API
     */
    public const PRODUCTION = 'production';
}
