<?php

declare(strict_types=1);

/*
 * OrdersLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace OrdersLib\Models;

use OrdersLib\ApiHelper;
use stdClass;

/**
 * The details of the refund status.
 */
class RefundStatusDetails implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $reason;

    /**
     * Returns Reason.
     * The reason why the refund has the `PENDING` or `FAILED` status.
     */
    public function getReason(): ?string
    {
        return $this->reason;
    }

    /**
     * Sets Reason.
     * The reason why the refund has the `PENDING` or `FAILED` status.
     *
     * @maps reason
     * @factory \OrdersLib\Models\RefundIncompleteReasonEnum::checkValue
     */
    public function setReason(?string $reason): void
    {
        $this->reason = $reason;
    }

    /**
     * Converts the RefundStatusDetails object to a human-readable string representation.
     *
     * @return string The string representation of the RefundStatusDetails object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('RefundStatusDetails', ['reason' => $this->reason]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->reason)) {
            $json['reason'] = RefundIncompleteReasonEnum::checkValue($this->reason);
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
