<?php

declare(strict_types=1);

/*
 * OrdersLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace OrdersLib\Tests;

use Core\Types\CallbackCatcher;
use OrdersLib\Authentication\ClientCredentialsAuthCredentialsBuilder;
use OrdersLib\OrdersClient;
use OrdersLib\OrdersClientBuilder;

class ClientFactory
{
    public static function create(CallbackCatcher $httpCallback): OrdersClient
    {
        $clientBuilder = OrdersClientBuilder::init();
        $clientBuilder = self::addConfigurationFromEnvironment($clientBuilder);
        $clientBuilder = self::addTestConfiguration($clientBuilder);
        return $clientBuilder->httpCallback($httpCallback)->build();
    }

    public static function addTestConfiguration(OrdersClientBuilder $builder): OrdersClientBuilder
    {
        return $builder;
    }

    public static function addConfigurationFromEnvironment(OrdersClientBuilder $builder): OrdersClientBuilder
    {
        $timeout = getenv('ORDERS_LIB_TIMEOUT');
        $numberOfRetries = getenv('ORDERS_LIB_NUMBER_OF_RETRIES');
        $maximumRetryWaitTime = getenv('ORDERS_LIB_MAXIMUM_RETRY_WAIT_TIME');
        $environment = getenv('ORDERS_LIB_ENVIRONMENT');
        $oAuthClientId = getenv('ORDERS_LIB_O_AUTH_CLIENT_ID');
        $oAuthClientSecret = getenv('ORDERS_LIB_O_AUTH_CLIENT_SECRET');

        if (!empty($timeout) && \is_numeric($timeout)) {
            $builder->timeout(intval($timeout));
        }

        if (!empty($numberOfRetries) && \is_numeric($numberOfRetries)) {
            $builder->numberOfRetries(intval($numberOfRetries));
        }

        if (!empty($maximumRetryWaitTime) && \is_numeric($maximumRetryWaitTime)) {
            $builder->maximumRetryWaitTime(intval($maximumRetryWaitTime));
        }

        if (!empty($environment)) {
            $builder->environment($environment);
        }

        if (!empty($oAuthClientId) && !empty($oAuthClientSecret)) {
            $builder->clientCredentialsAuthCredentials(
                ClientCredentialsAuthCredentialsBuilder::init($oAuthClientId, $oAuthClientSecret)
            );
        }

        return $builder;
    }
}
