<?php

declare(strict_types=1);

/*
 * PaypalRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaypalRestApisLib\Models;

/**
 * The reason why the authorized status is `PENDING`.
 */
class AuthorizationIncompleteReason
{
    public const PENDING_REVIEW = 'PENDING_REVIEW';

    public const DECLINED_BY_RISK_FRAUD_FILTERS = 'DECLINED_BY_RISK_FRAUD_FILTERS';
}
