<?php

declare(strict_types=1);

/*
 * PaypalRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaypalRestApisLib\Models;

/**
 * The status for the authorized payment.
 */
class AuthorizationStatus
{
    public const CREATED = 'CREATED';

    public const CAPTURED = 'CAPTURED';

    public const DENIED = 'DENIED';

    public const PARTIALLY_CAPTURED = 'PARTIALLY_CAPTURED';

    public const VOIDED = 'VOIDED';

    public const PENDING = 'PENDING';
}
