<?php

declare(strict_types=1);

/*
 * PaypalRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaypalRestApisLib\Models;

/**
 * The method used for card verification.
 */
class CardVerificationMethod
{
    public const SCA_ALWAYS = 'SCA_ALWAYS';

    public const SCA_WHEN_REQUIRED = 'SCA_WHEN_REQUIRED';

    public const ENUM_3D_SECURE = '3D_SECURE';

    public const AVS_CVV = 'AVS_CVV';
}
