<?php

declare(strict_types=1);

/*
 * PaypalRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaypalRestApisLib\Models;

/**
 * The intent to either capture payment immediately or authorize a payment for an order after order
 * creation.
 */
class CheckoutPaymentIntent
{
    public const CAPTURE = 'CAPTURE';

    public const AUTHORIZE = 'AUTHORIZE';
}
