<?php

declare(strict_types=1);

/*
 * PaypalRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaypalRestApisLib\Models;

/**
 * The condition that is covered for the transaction.
 */
class DisputeCategory
{
    public const ITEM_NOT_RECEIVED = 'ITEM_NOT_RECEIVED';

    public const UNAUTHORIZED_TRANSACTION = 'UNAUTHORIZED_TRANSACTION';
}
