<?php

declare(strict_types=1);

/*
 * PaypalRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaypalRestApisLib\Models;

/**
 * Status of Authentication eligibility.
 */
class EnrollmentStatus
{
    public const Y = 'Y';

    public const N = 'N';

    public const U = 'U';

    public const B = 'B';
}
