<?php

declare(strict_types=1);

/*
 * PaypalRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaypalRestApisLib\Models;

/**
 * The authorization status of the wallet instrument.
 */
class InstrumentAuthorizationStatus
{
    public const AUTHORIZED = 'AUTHORIZED';

    public const BLOCKED = 'BLOCKED';

    public const FAILED = 'FAILED';

    public const NOT_APPLICABLE = 'NOT_APPLICABLE';

    public const NOT_SUPPORTED = 'NOT_SUPPORTED';

    public const UNAUTHORIZED = 'UNAUTHORIZED';
}
