<?php

declare(strict_types=1);

/*
 * PaypalRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaypalRestApisLib\Models;

/**
 * The operation.
 */
class PatchOp
{
    public const ADD = 'add';

    public const REMOVE = 'remove';

    public const REPLACE = 'replace';

    public const MOVE = 'move';

    public const COPY = 'copy';

    public const TEST = 'test';
}
