<?php

declare(strict_types=1);

/*
 * PaypalRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaypalRestApisLib\Models;

/**
 * The declined payment transactions might have payment advice codes. The card networks, like Visa and
 * Mastercard, return payment advice codes.
 */
class PaymentAdviceCode
{
    public const ENUM_01 = '01';

    public const ENUM_02 = '02';

    public const ENUM_03 = '03';

    public const ENUM_21 = '21';
}
