<?php

declare(strict_types=1);

/*
 * PaypalRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaypalRestApisLib\Models;

/**
 * The person or party who initiated or triggered the payment.
 */
class PaymentInitiator
{
    public const CUSTOMER = 'CUSTOMER';

    public const MERCHANT = 'MERCHANT';
}
