<?php

declare(strict_types=1);

/*
 * PaypalRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaypalRestApisLib\Models;

/**
 * The vault status.
 */
class PaypalWalletVaultStatus
{
    public const VAULTED = 'VAULTED';

    public const CREATED = 'CREATED';

    public const APPROVED = 'APPROVED';
}
