<?php

declare(strict_types=1);

/*
 * PaypalRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaypalRestApisLib\Models;

/**
 * Configures a <strong>Continue</strong> or <strong>Pay Now</strong> checkout flow.
 */
class PaypalExperienceUserAction
{
    public const CONTINUE_ = 'CONTINUE';

    public const PAY_NOW = 'PAY_NOW';
}
