<?php

declare(strict_types=1);

/*
 * PaypalRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaypalRestApisLib\Models;

/**
 * The account status indicates whether the buyer has verified the financial details associated with
 * their PayPal account.
 */
class PaypalWalletAccountVerificationStatus
{
    public const VERIFIED = 'VERIFIED';

    public const UNVERIFIED = 'UNVERIFIED';
}
