<?php

declare(strict_types=1);

/*
 * PaypalRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaypalRestApisLib\Models;

/**
 * The usage type associated with the PayPal payment token.
 */
class PaypalPaymentTokenUsageType
{
    public const MERCHANT = 'MERCHANT';

    public const PLATFORM = 'PLATFORM';
}
