<?php

declare(strict_types=1);

/*
 * PaypalRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaypalRestApisLib\Models;

/**
 * Expected business/pricing model for the billing agreement.
 */
class PaypalPaymentTokenUsagePattern
{
    public const IMMEDIATE = 'IMMEDIATE';

    public const DEFERRED = 'DEFERRED';

    public const RECURRING_PREPAID = 'RECURRING_PREPAID';

    public const RECURRING_POSTPAID = 'RECURRING_POSTPAID';

    public const THRESHOLD_PREPAID = 'THRESHOLD_PREPAID';

    public const THRESHOLD_POSTPAID = 'THRESHOLD_POSTPAID';
}
