<?php

declare(strict_types=1);

/*
 * PaypalRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaypalRestApisLib\Models;

/**
 * Indicates if this is a `first` or `subsequent` payment using a stored payment source (also referred
 * to as stored credential or card on file).
 */
class StoredPaymentSourceUsageType
{
    public const FIRST = 'FIRST';

    public const SUBSEQUENT = 'SUBSEQUENT';

    public const DERIVED = 'DERIVED';
}
