<?php

declare(strict_types=1);

/*
 * PaypalRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaypalRestApisLib\Models;

/**
 * Indicates the type of the stored payment_source payment.
 */
class StoredPaymentSourcePaymentType
{
    public const ONE_TIME = 'ONE_TIME';

    public const RECURRING = 'RECURRING';

    public const UNSCHEDULED = 'UNSCHEDULED';
}
