<?php

declare(strict_types=1);

/*
 * PaypalRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaypalRestApisLib\Models;

/**
 * The customer's tax ID type.
 */
class TaxIdType
{
    public const BR_CPF = 'BR_CPF';

    public const BR_CNPJ = 'BR_CNPJ';
}
