<?php

declare(strict_types=1);

/*
 * PaypalRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaypalRestApisLib\Models;

/**
 * The tokenization method that generated the ID.
 */
class TokenType
{
    public const BILLING_AGREEMENT = 'BILLING_AGREEMENT';

    public const SETUP_TOKEN = 'SETUP_TOKEN';
}
