<?php

declare(strict_types=1);

/*
 * PaypalRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaypalRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use PaypalRestApisLib\Models\AchDebitResponse;

/**
 * Builder for model AchDebitResponse
 *
 * @see AchDebitResponse
 */
class AchDebitResponseBuilder
{
    /**
     * @var AchDebitResponse
     */
    private $instance;

    private function __construct(AchDebitResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Ach Debit Response Builder object.
     */
    public static function init(): self
    {
        return new self(new AchDebitResponse());
    }

    /**
     * Sets verification status field.
     *
     * @param string|null $value
     */
    public function verificationStatus(?string $value): self
    {
        $this->instance->setVerificationStatus($value);
        return $this;
    }

    /**
     * Initializes a new Ach Debit Response object.
     */
    public function build(): AchDebitResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
