<?php

declare(strict_types=1);

/*
 * PaypalRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaypalRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use PaypalRestApisLib\Models\AchDebitResponse;
use PaypalRestApisLib\Models\BankPaymentToken;
use PaypalRestApisLib\Models\SepaDebitResponse;

/**
 * Builder for model BankPaymentToken
 *
 * @see BankPaymentToken
 */
class BankPaymentTokenBuilder
{
    /**
     * @var BankPaymentToken
     */
    private $instance;

    private function __construct(BankPaymentToken $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Bank Payment Token Builder object.
     */
    public static function init(): self
    {
        return new self(new BankPaymentToken());
    }

    /**
     * Sets ach debit field.
     *
     * @param AchDebitResponse|null $value
     */
    public function achDebit(?AchDebitResponse $value): self
    {
        $this->instance->setAchDebit($value);
        return $this;
    }

    /**
     * Sets sepa debit field.
     *
     * @param SepaDebitResponse|null $value
     */
    public function sepaDebit(?SepaDebitResponse $value): self
    {
        $this->instance->setSepaDebit($value);
        return $this;
    }

    /**
     * Initializes a new Bank Payment Token object.
     */
    public function build(): BankPaymentToken
    {
        return CoreHelper::clone($this->instance);
    }
}
