<?php

declare(strict_types=1);

/*
 * PaypalRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaypalRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use PaypalRestApisLib\Models\BlikOneClickPaymentObject;

/**
 * Builder for model BlikOneClickPaymentObject
 *
 * @see BlikOneClickPaymentObject
 */
class BlikOneClickPaymentObjectBuilder
{
    /**
     * @var BlikOneClickPaymentObject
     */
    private $instance;

    private function __construct(BlikOneClickPaymentObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Blik One Click Payment Object Builder object.
     */
    public static function init(): self
    {
        return new self(new BlikOneClickPaymentObject());
    }

    /**
     * Sets consumer reference field.
     *
     * @param string|null $value
     */
    public function consumerReference(?string $value): self
    {
        $this->instance->setConsumerReference($value);
        return $this;
    }

    /**
     * Initializes a new Blik One Click Payment Object object.
     */
    public function build(): BlikOneClickPaymentObject
    {
        return CoreHelper::clone($this->instance);
    }
}
