<?php

declare(strict_types=1);

/*
 * PaypalRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaypalRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use PaypalRestApisLib\Models\CobrandedCard;
use PaypalRestApisLib\Models\Money;
use PaypalRestApisLib\Models\PayeeBase;

/**
 * Builder for model CobrandedCard
 *
 * @see CobrandedCard
 */
class CobrandedCardBuilder
{
    /**
     * @var CobrandedCard
     */
    private $instance;

    private function __construct(CobrandedCard $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Cobranded Card Builder object.
     */
    public static function init(): self
    {
        return new self(new CobrandedCard());
    }

    /**
     * Sets labels field.
     *
     * @param string[]|null $value
     */
    public function labels(?array $value): self
    {
        $this->instance->setLabels($value);
        return $this;
    }

    /**
     * Sets payee field.
     *
     * @param PayeeBase|null $value
     */
    public function payee(?PayeeBase $value): self
    {
        $this->instance->setPayee($value);
        return $this;
    }

    /**
     * Sets amount field.
     *
     * @param Money|null $value
     */
    public function amount(?Money $value): self
    {
        $this->instance->setAmount($value);
        return $this;
    }

    /**
     * Initializes a new Cobranded Card object.
     */
    public function build(): CobrandedCard
    {
        return CoreHelper::clone($this->instance);
    }
}
