<?php

declare(strict_types=1);

/*
 * PaypalRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaypalRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use PaypalRestApisLib\Models\CustomerRequest;

/**
 * Builder for model CustomerRequest
 *
 * @see CustomerRequest
 */
class CustomerRequestBuilder
{
    /**
     * @var CustomerRequest
     */
    private $instance;

    private function __construct(CustomerRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Customer Request Builder object.
     */
    public static function init(): self
    {
        return new self(new CustomerRequest());
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets merchant customer id field.
     *
     * @param string|null $value
     */
    public function merchantCustomerId(?string $value): self
    {
        $this->instance->setMerchantCustomerId($value);
        return $this;
    }

    /**
     * Initializes a new Customer Request object.
     */
    public function build(): CustomerRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
