<?php

declare(strict_types=1);

/*
 * PaypalRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaypalRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use PaypalRestApisLib\Models\EpsPaymentRequest;
use PaypalRestApisLib\Models\ExperienceContext;

/**
 * Builder for model EpsPaymentRequest
 *
 * @see EpsPaymentRequest
 */
class EpsPaymentRequestBuilder
{
    /**
     * @var EpsPaymentRequest
     */
    private $instance;

    private function __construct(EpsPaymentRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Eps Payment Request Builder object.
     *
     * @param string $name
     * @param string $countryCode
     */
    public static function init(string $name, string $countryCode): self
    {
        return new self(new EpsPaymentRequest($name, $countryCode));
    }

    /**
     * Sets experience context field.
     *
     * @param ExperienceContext|null $value
     */
    public function experienceContext(?ExperienceContext $value): self
    {
        $this->instance->setExperienceContext($value);
        return $this;
    }

    /**
     * Initializes a new Eps Payment Request object.
     */
    public function build(): EpsPaymentRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
