<?php

declare(strict_types=1);

/*
 * PaypalRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaypalRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use PaypalRestApisLib\Models\CardVerification;
use PaypalRestApisLib\Models\GooglePayCardAttributes;

/**
 * Builder for model GooglePayCardAttributes
 *
 * @see GooglePayCardAttributes
 */
class GooglePayCardAttributesBuilder
{
    /**
     * @var GooglePayCardAttributes
     */
    private $instance;

    private function __construct(GooglePayCardAttributes $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Google Pay Card Attributes Builder object.
     */
    public static function init(): self
    {
        return new self(new GooglePayCardAttributes());
    }

    /**
     * Sets verification field.
     *
     * @param CardVerification|null $value
     */
    public function verification(?CardVerification $value): self
    {
        $this->instance->setVerification($value);
        return $this;
    }

    /**
     * Initializes a new Google Pay Card Attributes object.
     */
    public function build(): GooglePayCardAttributes
    {
        return CoreHelper::clone($this->instance);
    }
}
