<?php

declare(strict_types=1);

/*
 * PaypalRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaypalRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use PaypalRestApisLib\Models\AuthorizationWithAdditionalData;
use PaypalRestApisLib\Models\Capture;
use PaypalRestApisLib\Models\PaymentCollection;
use PaypalRestApisLib\Models\Refund;

/**
 * Builder for model PaymentCollection
 *
 * @see PaymentCollection
 */
class PaymentCollectionBuilder
{
    /**
     * @var PaymentCollection
     */
    private $instance;

    private function __construct(PaymentCollection $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Payment Collection Builder object.
     */
    public static function init(): self
    {
        return new self(new PaymentCollection());
    }

    /**
     * Sets authorizations field.
     *
     * @param AuthorizationWithAdditionalData[]|null $value
     */
    public function authorizations(?array $value): self
    {
        $this->instance->setAuthorizations($value);
        return $this;
    }

    /**
     * Sets captures field.
     *
     * @param Capture[]|null $value
     */
    public function captures(?array $value): self
    {
        $this->instance->setCaptures($value);
        return $this;
    }

    /**
     * Sets refunds field.
     *
     * @param Refund[]|null $value
     */
    public function refunds(?array $value): self
    {
        $this->instance->setRefunds($value);
        return $this;
    }

    /**
     * Initializes a new Payment Collection object.
     */
    public function build(): PaymentCollection
    {
        return CoreHelper::clone($this->instance);
    }
}
