<?php

declare(strict_types=1);

/*
 * PaypalRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaypalRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use PaypalRestApisLib\Models\ApplePayPaymentToken;
use PaypalRestApisLib\Models\BankPaymentToken;
use PaypalRestApisLib\Models\CardPaymentToken;
use PaypalRestApisLib\Models\PaymentTokenResponsePaymentSource;
use PaypalRestApisLib\Models\PaypalPaymentToken;
use PaypalRestApisLib\Models\VenmoPaymentToken;

/**
 * Builder for model PaymentTokenResponsePaymentSource
 *
 * @see PaymentTokenResponsePaymentSource
 */
class PaymentTokenResponsePaymentSourceBuilder
{
    /**
     * @var PaymentTokenResponsePaymentSource
     */
    private $instance;

    private function __construct(PaymentTokenResponsePaymentSource $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Payment Token Response Payment Source Builder object.
     */
    public static function init(): self
    {
        return new self(new PaymentTokenResponsePaymentSource());
    }

    /**
     * Sets card field.
     *
     * @param CardPaymentToken|null $value
     */
    public function card(?CardPaymentToken $value): self
    {
        $this->instance->setCard($value);
        return $this;
    }

    /**
     * Sets paypal field.
     *
     * @param PaypalPaymentToken|null $value
     */
    public function paypal(?PaypalPaymentToken $value): self
    {
        $this->instance->setPaypal($value);
        return $this;
    }

    /**
     * Sets venmo field.
     *
     * @param VenmoPaymentToken|null $value
     */
    public function venmo(?VenmoPaymentToken $value): self
    {
        $this->instance->setVenmo($value);
        return $this;
    }

    /**
     * Sets apple pay field.
     *
     * @param ApplePayPaymentToken|null $value
     */
    public function applePay(?ApplePayPaymentToken $value): self
    {
        $this->instance->setApplePay($value);
        return $this;
    }

    /**
     * Sets bank field.
     *
     * @param BankPaymentToken|null $value
     */
    public function bank(?BankPaymentToken $value): self
    {
        $this->instance->setBank($value);
        return $this;
    }

    /**
     * Initializes a new Payment Token Response Payment Source object.
     */
    public function build(): PaymentTokenResponsePaymentSource
    {
        return CoreHelper::clone($this->instance);
    }
}
