<?php

declare(strict_types=1);

/*
 * PaypalRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaypalRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use PaypalRestApisLib\Models\SepaDebitAuthorizationDetails;

/**
 * Builder for model SepaDebitAuthorizationDetails
 *
 * @see SepaDebitAuthorizationDetails
 */
class SepaDebitAuthorizationDetailsBuilder
{
    /**
     * @var SepaDebitAuthorizationDetails
     */
    private $instance;

    private function __construct(SepaDebitAuthorizationDetails $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Sepa Debit Authorization Details Builder object.
     */
    public static function init(): self
    {
        return new self(new SepaDebitAuthorizationDetails());
    }

    /**
     * Sets status field.
     *
     * @param string|null $value
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Initializes a new Sepa Debit Authorization Details object.
     */
    public function build(): SepaDebitAuthorizationDetails
    {
        return CoreHelper::clone($this->instance);
    }
}
