<?php

declare(strict_types=1);

/*
 * PaypalRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaypalRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use PaypalRestApisLib\Models\Address;
use PaypalRestApisLib\Models\SetupTokenCardExperienceContext;
use PaypalRestApisLib\Models\SetupTokenRequestCard;

/**
 * Builder for model SetupTokenRequestCard
 *
 * @see SetupTokenRequestCard
 */
class SetupTokenRequestCardBuilder
{
    /**
     * @var SetupTokenRequestCard
     */
    private $instance;

    private function __construct(SetupTokenRequestCard $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Setup Token Request Card Builder object.
     */
    public static function init(): self
    {
        return new self(new SetupTokenRequestCard());
    }

    /**
     * Sets name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets number field.
     *
     * @param string|null $value
     */
    public function number(?string $value): self
    {
        $this->instance->setNumber($value);
        return $this;
    }

    /**
     * Sets expiry field.
     *
     * @param string|null $value
     */
    public function expiry(?string $value): self
    {
        $this->instance->setExpiry($value);
        return $this;
    }

    /**
     * Sets security code field.
     *
     * @param string|null $value
     */
    public function securityCode(?string $value): self
    {
        $this->instance->setSecurityCode($value);
        return $this;
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets brand field.
     *
     * @param string|null $value
     */
    public function brand(?string $value): self
    {
        $this->instance->setBrand($value);
        return $this;
    }

    /**
     * Sets billing address field.
     *
     * @param Address|null $value
     */
    public function billingAddress(?Address $value): self
    {
        $this->instance->setBillingAddress($value);
        return $this;
    }

    /**
     * Sets verification method field.
     *
     * @param string|null $value
     */
    public function verificationMethod(?string $value): self
    {
        $this->instance->setVerificationMethod($value);
        return $this;
    }

    /**
     * Sets experience context field.
     *
     * @param SetupTokenCardExperienceContext|null $value
     */
    public function experienceContext(?SetupTokenCardExperienceContext $value): self
    {
        $this->instance->setExperienceContext($value);
        return $this;
    }

    /**
     * Sets network transaction reference field.
     *
     * @param mixed $value
     */
    public function networkTransactionReference($value): self
    {
        $this->instance->setNetworkTransactionReference($value);
        return $this;
    }

    /**
     * Initializes a new Setup Token Request Card object.
     */
    public function build(): SetupTokenRequestCard
    {
        return CoreHelper::clone($this->instance);
    }
}
