<?php

declare(strict_types=1);

/*
 * PaypalRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaypalRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use PaypalRestApisLib\Models\Address;
use PaypalRestApisLib\Models\ShippingName;
use PaypalRestApisLib\Models\VaultedDigitalWalletShippingDetails;

/**
 * Builder for model VaultedDigitalWalletShippingDetails
 *
 * @see VaultedDigitalWalletShippingDetails
 */
class VaultedDigitalWalletShippingDetailsBuilder
{
    /**
     * @var VaultedDigitalWalletShippingDetails
     */
    private $instance;

    private function __construct(VaultedDigitalWalletShippingDetails $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Vaulted Digital Wallet Shipping Details Builder object.
     */
    public static function init(): self
    {
        return new self(new VaultedDigitalWalletShippingDetails());
    }

    /**
     * Sets name field.
     *
     * @param ShippingName|null $value
     */
    public function name(?ShippingName $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets address field.
     *
     * @param Address|null $value
     */
    public function address(?Address $value): self
    {
        $this->instance->setAddress($value);
        return $this;
    }

    /**
     * Initializes a new Vaulted Digital Wallet Shipping Details object.
     */
    public function build(): VaultedDigitalWalletShippingDetails
    {
        return CoreHelper::clone($this->instance);
    }
}
