<?php

declare(strict_types=1);

/*
 * PaypalRestApisLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaypalRestApisLib\Models\Builders;

use Core\Utils\CoreHelper;
use PaypalRestApisLib\Models\Address;
use PaypalRestApisLib\Models\VaultSepaDebitResponse;

/**
 * Builder for model VaultSepaDebitResponse
 *
 * @see VaultSepaDebitResponse
 */
class VaultSepaDebitResponseBuilder
{
    /**
     * @var VaultSepaDebitResponse
     */
    private $instance;

    private function __construct(VaultSepaDebitResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Vault Sepa Debit Response Builder object.
     */
    public static function init(): self
    {
        return new self(new VaultSepaDebitResponse());
    }

    /**
     * Sets iban last chars field.
     *
     * @param string|null $value
     */
    public function ibanLastChars(?string $value): self
    {
        $this->instance->setIbanLastChars($value);
        return $this;
    }

    /**
     * Sets account holder name field.
     *
     * @param mixed $value
     */
    public function accountHolderName($value): self
    {
        $this->instance->setAccountHolderName($value);
        return $this;
    }

    /**
     * Sets billing address field.
     *
     * @param Address|null $value
     */
    public function billingAddress(?Address $value): self
    {
        $this->instance->setBillingAddress($value);
        return $this;
    }

    /**
     * Initializes a new Vault Sepa Debit Response object.
     */
    public function build(): VaultSepaDebitResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
